export const EventKeyCodeToJSID = new Map([
    ["Backspace","0"],
    ["Tab","1"],
    ["Enter","2"],
    ["ShiftLeft","3"],
    ["ShiftRight","4"],
    ["ControlLeft","5"],
    ["ControlRight","6"],
    ["AltLeft","7"],
    ["AltRight","8"],
    ["CapsLock","9"],
    ["Space","10"],
    // ["PageUp","11"],
    // ["PageDown","12"],
    // ["End","13"],
    // ["Home","14"],
    ["ArrowLeft","15"],
    // ["ArrowUp","16"],
    ["ArrowRight","17"],
    // ["ArrowDown","18"],
    // ["Insert","19"],
    // ["Delete","20"],
    ["Digit0","21"],
    ["Digit1","22"],
    ["Digit2","23"],
    ["Digit3","24"],
    ["Digit4","25"],
    ["Digit5","26"],
    ["Digit6","27"],
    ["Digit7","28"],
    ["Digit8","29"],
    ["Digit9","30"],
    ["KeyA","31"],
    ["KeyB","32"],
    ["KeyC","33"],
    ["KeyD","34"],
    ["KeyE","35"],
    ["KeyF","36"],
    ["KeyG","37"],
    ["KeyH","38"],
    ["KeyI","39"],
    ["KeyJ","40"],
    ["KeyK","41"],
    ["KeyL","42"],
    ["KeyM","43"],
    ["KeyN","44"],
    ["KeyO","45"],
    ["KeyP","46"],
    ["KeyQ","47"],
    ["KeyR","48"],
    ["KeyS","49"],
    ["KeyT","50"],
    ["KeyU","51"],
    ["KeyV","52"],
    ["KeyW","53"],
    ["KeyX","54"],
    ["KeyY","55"],
    ["KeyZ","56"],
    ["Semicolon","57"],
    ["Equal","58"],
    ["Comma","59"],
    ["Minus","60"],
    ["Period","61"],
    ["Slash","62"],
    ["Backquote","63"],
    ["BracketLeft","64"],
    ["Backslash","65"],
    ["BracketRight","66"],
    ["Quote","67"],
]);

export const EventKeyCodeToJSID_inverse = new Map(
    [...EventKeyCodeToJSID.entries()].map(x => [x[1], x[0]]))

export const KEYDOWN_EVENT = "keydown"
export const KEYUP_EVENT = "keyup"